name: list-changed-directories
description: Outputs a list of changed directories that include a target file

inputs:
  target-file:
    description: Filename that the output directories must include
    required: true

outputs:
  changed-directories:
    description: List of changed directories as a JSON string

runs:
  using: node20
  main: dist/index.js
