name: "list-changed-directories"
description: "Outputs a list of changed directories"

inputs:
  target-directories:
    description: "A list of directories to check for changes"
    default: |
      **
  target-file:
    description: "The file that must be included in the output directories"
    default: "*"

outputs:
  directories:
    description: "A list of directories that have changed"

runs:
  using: "node20"
  main: "dist/index.js"
