name: list-changed-directories
description: Outputs a list of directories that have changed and include a specified target file

inputs:
  target-file:
    description: A filename that must be included in the output directories
    required: true
  common-dependency-paths:
    description: >-
      Paths to files that all directories including the target-file depend on. If any of these files are changed,
      all directories including the target-file are considered changed.

outputs:
  changed-directories:
    description: The list of changed directories as a JSON string.

runs:
  using: node20
  main: dist/index.js

branding:
  icon: list
  color: blue
